env:
  browser: true
  es2021: true
  jest: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-underscore-dangle: [2, { "allow": ["__dirname", "__filename"] }]
